/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedExcelRouteImport } from './routes/_authenticated/excel'
import { Route as AuthenticatedIssueRouteImport } from './routes/_authenticated/issue'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedReceiveRouteImport } from './routes/_authenticated/receive'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExcelRoute = AuthenticatedExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIssueRoute = AuthenticatedIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiveRoute = AuthenticatedReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/excel': typeof AuthenticatedExcelRoute
  '/issue': typeof AuthenticatedIssueRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/excel': typeof AuthenticatedExcelRoute
  '/issue': typeof AuthenticatedIssueRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/excel': typeof AuthenticatedExcelRoute
  '/_authenticated/issue': typeof AuthenticatedIssueRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/receive': typeof AuthenticatedReceiveRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/excel'
    | '/issue'
    | '/ledger'
    | '/receive'
    | '/users'
    | '/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/excel'
    | '/issue'
    | '/ledger'
    | '/receive'
    | '/users'
    | '/vouchers'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/excel'
    | '/_authenticated/issue'
    | '/_authenticated/ledger'
    | '/_authenticated/receive'
    | '/_authenticated/users'
    | '/_authenticated/vouchers'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/excel': {
      id: '/_authenticated/excel'
      path: '/excel'
      fullPath: '/excel'
      preLoaderRoute: typeof AuthenticatedExcelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issue': {
      id: '/_authenticated/issue'
      path: '/issue'
      fullPath: '/issue'
      preLoaderRoute: typeof AuthenticatedIssueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receive': {
      id: '/_authenticated/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AuthenticatedReceiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExcelRoute: typeof AuthenticatedExcelRoute
  AuthenticatedIssueRoute: typeof AuthenticatedIssueRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedReceiveRoute: typeof AuthenticatedReceiveRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExcelRoute: AuthenticatedExcelRoute,
  AuthenticatedIssueRoute: AuthenticatedIssueRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedReceiveRoute: AuthenticatedReceiveRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
